-- DropForeignKey
ALTER TABLE "EMPLOYEE" DROP CONSTRAINT "EMPLOYEE_COD_WORK_PERIOD_fkey";

-- AlterTable
ALTER TABLE "EMPLOYEE" ALTER COLUMN "COD_WORK_PERIOD" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_COD_WORK_PERIOD_fkey" FOREIGN KEY ("COD_WORK_PERIOD") REFERENCES "WORK_PERIOD"("COD_WORK_PERIOD") ON DELETE SET NULL ON UPDATE CASCADE;
