-- CreateEnum
CREATE TYPE "UserType" AS ENUM ('COMPANY', 'EMPLOYEE');

-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('BASIC', 'ADMIN');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('PENDING', 'ACTIVE', 'DISABLED');

-- CreateEnum
CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'ANOTHER');

-- CreateEnum
CREATE TYPE "AcessMethods" AS ENUM ('WEB', 'APP', 'WEB_APP');

-- CreateEnum
CREATE TYPE "AbsenceType" AS ENUM ('LEAVE_OF_ABSENCE', 'MEDICAL_CERTIFICATE', 'LEGAL', 'ABSENCE', 'UNJUSTIFIED', 'VACATION', 'DAY', 'INSS', 'SUSPENSION');

-- CreateEnum
CREATE TYPE "Weekday" AS ENUM ('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');

-- CreateTable
CREATE TABLE "USER" (
    "IDT_USER" TEXT NOT NULL,
    "IDT_COMPANY" TEXT,
    "NAM_NAME" TEXT NOT NULL,
    "NAM_EMAIL" TEXT NOT NULL,
    "NAM_PASSWORD" TEXT NOT NULL,
    "IND_TYPE" "UserType" NOT NULL,
    "IND_STATUS" "UserStatus" NOT NULL DEFAULT 'PENDING',
    "NAM_RESET_TOKEN" TEXT,
    "NAM_CONFIRMATION_TOKEN" TEXT,
    "IND_ROLE" "UserRole" NOT NULL DEFAULT 'BASIC',
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("IDT_USER")
);

-- CreateTable
CREATE TABLE "COMPANY" (
    "IDT_COMPANY" TEXT NOT NULL,
    "IDT_ADDRESS" TEXT NOT NULL,
    "IDT_CATEGORY" TEXT NOT NULL,
    "NAM_SOCIAL_NAME" TEXT NOT NULL,
    "DOC_DOCUMENT" TEXT NOT NULL,
    "DES_PHONE" TEXT NOT NULL,
    "NUM_EMPLOYEE_QUANTITY" INTEGER NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "COMPANY_pkey" PRIMARY KEY ("IDT_COMPANY")
);

-- CreateTable
CREATE TABLE "ADDRESS" (
    "IDT_ADDRESS" TEXT NOT NULL,
    "DES_ADDRESS" TEXT NOT NULL,
    "NUM_LAT" TEXT NOT NULL,
    "NUM_LNG" TEXT NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ADDRESS_pkey" PRIMARY KEY ("IDT_ADDRESS")
);

-- CreateTable
CREATE TABLE "CATEGORY" (
    "IDT_CATEGORY" TEXT NOT NULL,
    "NAM_NAME" TEXT NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CATEGORY_pkey" PRIMARY KEY ("IDT_CATEGORY")
);

-- CreateTable
CREATE TABLE "EMPLOYEE" (
    "IDT_EMPLOYEE" TEXT NOT NULL,
    "IDT_USER" TEXT NOT NULL,
    "IDT_COMPANY" TEXT NOT NULL,
    "IND_GENDER" "Gender" NOT NULL,
    "COD_WORK_PERIOD" TEXT NOT NULL,
    "DOC_DOCUMENT" TEXT NOT NULL,
    "DAT_BIRTH" TEXT NOT NULL,
    "DES_PHONE" TEXT NOT NULL,
    "NUM_HOURLY_WAGE" DOUBLE PRECISION NOT NULL,
    "COD_NIS_PIS" TEXT,
    "IND_ACESS_METHOD" "AcessMethods" NOT NULL,
    "COD_REGISTER" TEXT NOT NULL,
    "DAT_ADMISSION" TEXT NOT NULL,
    "FLG_ENABLE_APP" BOOLEAN NOT NULL DEFAULT true,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "DAT_INICIAL" TEXT NOT NULL,
    "FLG_PRESENCE" BOOLEAN NOT NULL DEFAULT true,
    "IND_OFFICE" TEXT NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EMPLOYEE_pkey" PRIMARY KEY ("IDT_EMPLOYEE")
);

-- CreateTable
CREATE TABLE "ABSENCE" (
    "IDT_ABSENCE" TEXT NOT NULL,
    "IDT_EMPLOYEE" TEXT NOT NULL,
    "IDT_COMPANY" TEXT NOT NULL,
    "IND_ABSENCE_TYPE" "AbsenceType" NOT NULL,
    "DESC_DESCRIPTION" TEXT NOT NULL,
    "DAT_INITIAL" TIMESTAMP(3) NOT NULL,
    "DAT_END" TIMESTAMP(3) NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ABSENCE_pkey" PRIMARY KEY ("IDT_ABSENCE")
);

-- CreateTable
CREATE TABLE "ATTACHMENT" (
    "IDT_ATTACHMENT" TEXT NOT NULL,
    "IDT_ABSENCE" TEXT NOT NULL,
    "NAM_URL" TEXT NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ATTACHMENT_pkey" PRIMARY KEY ("IDT_ATTACHMENT")
);

-- CreateTable
CREATE TABLE "WORK_PERIOD" (
    "IDT_WORK_PERIOD" TEXT NOT NULL,
    "COD_WORK_PERIOD" TEXT NOT NULL,
    "IND_WEEKDAY" "Weekday" NOT NULL,
    "IDT_COMPANY" TEXT NOT NULL,
    "NAM_NAME" TEXT NOT NULL,
    "DAT_START_WORK_HOUR" TIMESTAMP(3) NOT NULL,
    "DAT_FINISHED_WORK_HOUR" TIMESTAMP(3) NOT NULL,
    "DAT_START_BREAK_HOUR" TIMESTAMP(3) NOT NULL,
    "DAT_FINISHED_BREAK_HOUR" TIMESTAMP(3) NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WORK_PERIOD_pkey" PRIMARY KEY ("IDT_WORK_PERIOD")
);

-- CreateTable
CREATE TABLE "WORK_PERIOD_REGISTER" (
    "IDT_WORK_PERIOD_REGISTER" TEXT NOT NULL,
    "IDT_WORK_PERIOD" TEXT,
    "IDT_EMPLOYEE" TEXT NOT NULL,
    "DAT_START_HOUR" TIMESTAMP(3) NOT NULL,
    "DAT_END_HOUR" TIMESTAMP(3),
    "DAT_START_BREAK_HOUR" TIMESTAMP(3),
    "DAT_FINISHED_WORK_HOUR" TIMESTAMP(3),
    "NUM_LAT" TEXT NOT NULL,
    "NUM_LNG" TEXT NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WORK_PERIOD_REGISTER_pkey" PRIMARY KEY ("IDT_WORK_PERIOD_REGISTER")
);

-- CreateTable
CREATE TABLE "EXTRA_WORK_PERIOD" (
    "IDT_EXTRA_WORK_PERIOD" TEXT NOT NULL,
    "IDT_WORK_PERIOD" TEXT NOT NULL,
    "IDT_EMPLOYEE" TEXT NOT NULL,
    "DAT_EXTRA_START_WORK_HOUR" TIMESTAMP(3) NOT NULL,
    "DAT_EXTRA_FINISHED_WORK_HOUR" TIMESTAMP(3) NOT NULL,
    "DAT_START_BREAK_HOUR" TIMESTAMP(3) NOT NULL,
    "DAT_FINISHED_WORK_HOUR" TIMESTAMP(3) NOT NULL,
    "NUM_LAT" TEXT NOT NULL,
    "NUM_LNG" TEXT NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EXTRA_WORK_PERIOD_pkey" PRIMARY KEY ("IDT_EXTRA_WORK_PERIOD")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_NAM_EMAIL_key" ON "USER"("NAM_EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "USER_NAM_RESET_TOKEN_key" ON "USER"("NAM_RESET_TOKEN");

-- CreateIndex
CREATE UNIQUE INDEX "USER_NAM_CONFIRMATION_TOKEN_key" ON "USER"("NAM_CONFIRMATION_TOKEN");

-- CreateIndex
CREATE INDEX "IDX_USER_COMPANY_ID" ON "USER"("IDT_COMPANY");

-- CreateIndex
CREATE INDEX "IDX_NAME" ON "USER"("NAM_NAME");

-- CreateIndex
CREATE INDEX "IDX_USER_EMAIL" ON "USER"("NAM_EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "COMPANY_IDT_ADDRESS_key" ON "COMPANY"("IDT_ADDRESS");

-- CreateIndex
CREATE UNIQUE INDEX "COMPANY_DOC_DOCUMENT_key" ON "COMPANY"("DOC_DOCUMENT");

-- CreateIndex
CREATE INDEX "IDX_COMPANY_DOCUMENT" ON "COMPANY"("DOC_DOCUMENT");

-- CreateIndex
CREATE UNIQUE INDEX "CATEGORY_NAM_NAME_key" ON "CATEGORY"("NAM_NAME");

-- CreateIndex
CREATE UNIQUE INDEX "EMPLOYEE_IDT_USER_key" ON "EMPLOYEE"("IDT_USER");

-- CreateIndex
CREATE UNIQUE INDEX "EMPLOYEE_COD_WORK_PERIOD_key" ON "EMPLOYEE"("COD_WORK_PERIOD");

-- CreateIndex
CREATE INDEX "IDX_EMPLOYEE_COMPANY_ID" ON "EMPLOYEE"("IDT_COMPANY");

-- CreateIndex
CREATE INDEX "IDX_DOCUMENT" ON "EMPLOYEE"("DOC_DOCUMENT");

-- CreateIndex
CREATE INDEX "IDX_ABSENCE_COMPANY_ID" ON "ABSENCE"("IDT_COMPANY");

-- CreateIndex
CREATE INDEX "IDX_ABSENCE_EMPLOYEE_ID" ON "ABSENCE"("IDT_EMPLOYEE");

-- CreateIndex
CREATE UNIQUE INDEX "WORK_PERIOD_COD_WORK_PERIOD_key" ON "WORK_PERIOD"("COD_WORK_PERIOD");

-- CreateIndex
CREATE UNIQUE INDEX "WORK_PERIOD_IND_WEEKDAY_key" ON "WORK_PERIOD"("IND_WEEKDAY");

-- CreateIndex
CREATE INDEX "IDX_WORK_PERIOD_NAME" ON "WORK_PERIOD"("NAM_NAME");

-- CreateIndex
CREATE INDEX "IDX_WORK_PERIOD_COMPANY_ID" ON "WORK_PERIOD"("IDT_COMPANY");

-- CreateIndex
CREATE INDEX "IDX_WORK_PERIOD_REGISTER_EMPLOYEE_ID" ON "WORK_PERIOD_REGISTER"("IDT_EMPLOYEE");

-- AddForeignKey
ALTER TABLE "USER" ADD CONSTRAINT "USER_IDT_COMPANY_fkey" FOREIGN KEY ("IDT_COMPANY") REFERENCES "COMPANY"("IDT_COMPANY") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "COMPANY" ADD CONSTRAINT "COMPANY_IDT_CATEGORY_fkey" FOREIGN KEY ("IDT_CATEGORY") REFERENCES "CATEGORY"("IDT_CATEGORY") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "COMPANY" ADD CONSTRAINT "COMPANY_IDT_ADDRESS_fkey" FOREIGN KEY ("IDT_ADDRESS") REFERENCES "ADDRESS"("IDT_ADDRESS") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_IDT_USER_fkey" FOREIGN KEY ("IDT_USER") REFERENCES "USER"("IDT_USER") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_IDT_COMPANY_fkey" FOREIGN KEY ("IDT_COMPANY") REFERENCES "COMPANY"("IDT_COMPANY") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_COD_WORK_PERIOD_fkey" FOREIGN KEY ("COD_WORK_PERIOD") REFERENCES "WORK_PERIOD"("COD_WORK_PERIOD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ABSENCE" ADD CONSTRAINT "ABSENCE_IDT_COMPANY_fkey" FOREIGN KEY ("IDT_COMPANY") REFERENCES "COMPANY"("IDT_COMPANY") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ABSENCE" ADD CONSTRAINT "ABSENCE_IDT_EMPLOYEE_fkey" FOREIGN KEY ("IDT_EMPLOYEE") REFERENCES "EMPLOYEE"("IDT_EMPLOYEE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "ATTACHMENT_IDT_ABSENCE_fkey" FOREIGN KEY ("IDT_ABSENCE") REFERENCES "ABSENCE"("IDT_ABSENCE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WORK_PERIOD" ADD CONSTRAINT "WORK_PERIOD_IDT_COMPANY_fkey" FOREIGN KEY ("IDT_COMPANY") REFERENCES "COMPANY"("IDT_COMPANY") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WORK_PERIOD_REGISTER" ADD CONSTRAINT "WORK_PERIOD_REGISTER_IDT_WORK_PERIOD_fkey" FOREIGN KEY ("IDT_WORK_PERIOD") REFERENCES "WORK_PERIOD"("IDT_WORK_PERIOD") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WORK_PERIOD_REGISTER" ADD CONSTRAINT "WORK_PERIOD_REGISTER_IDT_EMPLOYEE_fkey" FOREIGN KEY ("IDT_EMPLOYEE") REFERENCES "EMPLOYEE"("IDT_EMPLOYEE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EXTRA_WORK_PERIOD" ADD CONSTRAINT "EXTRA_WORK_PERIOD_IDT_WORK_PERIOD_fkey" FOREIGN KEY ("IDT_WORK_PERIOD") REFERENCES "WORK_PERIOD"("IDT_WORK_PERIOD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EXTRA_WORK_PERIOD" ADD CONSTRAINT "EXTRA_WORK_PERIOD_IDT_EMPLOYEE_fkey" FOREIGN KEY ("IDT_EMPLOYEE") REFERENCES "EMPLOYEE"("IDT_EMPLOYEE") ON DELETE RESTRICT ON UPDATE CASCADE;
