export enum TypeAbsenceEnum {
  LEAVE_OF_ABSENCE = "LEAVE_OF_ABSENCE",
  MEDICAL_CERTIFICATE = "MEDICAL_CERTIFICATE",
  LEGAL = "LEGAL",
  ABSENCE = "ABSENCE",
  UNJUSTIFIED = "UNJUSTIFIED",
  VACATION = "VACATION",
  DAY = "DAY",
  INSS = "INSS",
  SUSPENSION = "SUSPENSION",
}
